# Scratchpad for personal exploration

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from src.dataset import ConnTextULDataset
from src.model import Model
import torch as torch

[nltk_data] Downloading package cmudict to
[nltk_data]     /Users/erlebach/nltk_data...
[nltk_data]   Package cmudict is already up-to-date!


In [3]:
import pandas as pd
df = pd.read_csv("data/data_test50.csv")
df.shape

(50, 1)

In [4]:
for size in [20, 50, 100, 250, 500, 1000]:
    new_df = df['word_raw'][torch.randint(low=0, high=50000, size=(size,)).tolist()]
    new_df.to_csv(f"data/data_test{size}.csv", index=False)

KeyError: "None of [Int64Index([48508, 10326, 14046, 25414, 24923, 39616, 20705, 14472, 30073,\n            27181, 42380, 31641, 45987, 13295,  9703, 48658, 38992, 29223,\n            31962,  6268],\n           dtype='int64')] are in the [index]"

In [4]:
new_df.to_csv("data/data_test.csv", index=False)

NameError: name 'new_df' is not defined

In [14]:
"""
ConnTextULDataset should have option to read less rows
should test: nb_rows, test, which_dataset
Test == True: 
  - Use which_data (nb_rows should be disabled)
Test == False
  - Randomly sample nb_rows. If nb_rows==None, read the entire dataset

Suggestion: add a shuffle=Bool to CnnTextULDataset constructor when test=False

Comment: vocabularies of orthography and phonology are independent of the input data size. Somehow,
I don't think that should be the case. It could mess up testing. 
"""

ds = ConnTextULDataset(nb_rows=None, test=False, which_dataset=5)
num_layers = 2
num_layers_dict={
    'orth_enc': num_layers,
    'orth_dec': num_layers,
    'phon_enc': num_layers,
    'phon_dec': num_layers,
    'mixing_enc': num_layers
}
d_model = 64
m = Model(orth_vocab_size=len(ds.character_tokenizer),
          phon_vocab_size=len(ds.phonology_tokenizer),
          d_model=d_model,
          d_embedding=1,  # for mixing
          max_orth_seq_len=ds.max_orth_seq_len,
          max_phon_seq_len=ds.max_phon_seq_len,
          nhead=4,
          num_layers_dict=num_layers_dict
          )
m.eval();  # returns self (i.e., m)
orth_vocab_size = len(ds.character_tokenizer)
phon_vocab_size = len(ds.phonology_tokenizer)
print("orth_vocab_size: ", orth_vocab_size)
print("phon_vocab_size: ", phon_vocab_size)
print("d_model: ", d_model)
print("ds.dataset.shape: ", ds.dataset.shape)

ConnText..., nb_rows:  None
ConnText..., which_dataset:  5
CURRENT FOLDER:  /Users/erlebach/src/2023/ConnTextUL
len(self.dataset):  (90544, 7)
orth position embedding: max_orth_seq_len:  11
orth_vocab_size:  49
phon_vocab_size:  34
d_model:  64
ds.dataset.shape:  (90544, 7)


In [15]:
print(list(ds.__dict__.keys()))
print(ds.dataset.shape)

['dataset', 'phonology_tokenizer', 'character_tokenizer', 'max_orth_seq_len', 'max_phon_seq_len', 'max_seq_len', 'words']
(90544, 7)


In [16]:
# self.vocab = ['[BOS]', '[EOS]', '[CLS]', '[UNK]', '[PAD]']
# Ortho ids
#      BOS: 0
#      EOS: 1
#      CLS: 2
#      UNK: 3
#      PAD: 4
# Phono Ids
#    BOS: 31  (0 0 0 0 ... 1 0 0)   (a 1 in 31st position)
#    EOS: 32  (0 0 0 0 ... 0 1 0)
#    PAD: 33  (0 0 0 0 ... 0 0 1)

idx = 10040  # What is idx?phon['enc_input_ids'].shape, 
idx = 10031
num_words = 5   # batch_size
word = ds.words[idx:idx+num_words]
print("words = ", word)
batch = ds[idx:idx+num_words]
#print("batch = ", batch)
orth, phon = batch['orthography'].to('cpu'), batch['phonology'].to('cpu')
# orth and phon are dicitonaries
# ids represent either a character or a phoneme
# Each word: 0,x,x,x,1,4  (padding is optional. 0 and 1 are mandatory)
print("orth['enc_input_ids'] = ", orth['enc_input_ids'].shape, orth['enc_input_ids'])  # batch_size, max_orth_size
print("orth['enc_pad_mask'] = ", orth['enc_pad_mask'].shape, orth['enc_pad_mask'])
# Each word: 0,x,x,x,4  (padding is optional. 0 is  mandatory) No EoS on decoder input. Why? 
# Only input into the decoder a character if the next character will be predicted. 
# Since one does not predict the character folling EoS, it does not have to be in the decoder input
print("orth['dec_input_ids'] = ", orth['dec_input_ids'].shape, orth['dec_input_ids'])
print("orth['dec_pad_mask'] = ", orth['dec_pad_mask'].shape, orth['dec_pad_mask'])
#print("phon['enc_input_ids'] = ", phon['enc_input_ids'].shape, phon['enc_input_ids'])
# phon: no "bOS and EOS" tokens. Why not? 
print("==> phon['enc_input_ids'] = ", len(phon['enc_input_ids']))
# Each phono is a list of integers: e.g. [3,5] corresponds to [0 0 0 1 0 1 0 0 0 0 ... 0 0 ]
#                                   e.g. [0,3,5] corresponds to [1 0 0 1 0 1 0 0 0 0 ... 0 0 ]
for  i in phon['enc_input_ids']:
    print("    ", i)

print("phon['enc_pad_mask'] = ", phon['enc_pad_mask'].shape, phon['enc_pad_mask'])
#print("phon['dec_input_ids'] = ", phon['dec_input_ids'].shape, phon['dec_input_ids'])
print("==> phon['dec_input_ids'] = ", len(phon['dec_input_ids']))
for i in phon['dec_input_ids']:
    print("     ", i)
print("==> phon['dec_input_ids'] = ", len(phon['dec_input_ids']))
print("phon['dec_pad_mask'] = ", phon['dec_pad_mask'].shape, phon['dec_pad_mask'])
print("phon['targets'] = ", phon['targets'].shape, phon['targets'])

words =  ['as', 'she', 'and', 'you', 'was']
orth['enc_input_ids'] =  torch.Size([5, 5]) tensor([[ 0, 11, 29,  1,  4],
        [ 0, 29, 18, 15,  1],
        [ 0, 11, 24, 14,  1],
        [ 0, 35, 25, 31,  1],
        [ 0, 33, 11, 29,  1]])
orth['enc_pad_mask'] =  torch.Size([5, 5]) tensor([[False, False, False, False,  True],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])
orth['dec_input_ids'] =  torch.Size([5, 4]) tensor([[ 0, 11, 29,  4],
        [ 0, 29, 18, 15],
        [ 0, 11, 24, 14],
        [ 0, 35, 25, 31],
        [ 0, 33, 11, 29]])
orth['dec_pad_mask'] =  torch.Size([5, 4]) tensor([[False, False, False,  True],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
==> phon['enc_input_ids'] =  5
     [tensor([31]), tensor([14, 15, 17, 22, 29]), te

In [32]:
z = m(orth_enc_input=orth['enc_input_ids'],
      orth_enc_pad_mask=orth['enc_pad_mask'],
      orth_dec_input=orth['dec_input_ids'],
      orth_dec_pad_mask=orth['dec_pad_mask'],
      phon_enc_input=phon['enc_input_ids'],
      phon_enc_pad_mask=phon['enc_pad_mask'],
      phon_dec_input=phon['dec_input_ids'],
      phon_dec_pad_mask=phon['dec_pad_mask']
      )

In [34]:
print(orth['enc_input_ids'].shape)
print(orth['enc_input_ids'][:,1:].shape)

torch.Size([5, 5])
torch.Size([5, 4])


In [24]:
print("z['orth'].shape", z['orth'].shape)
print("z['orth'] = ", z['orth'])
print("orth['enc_input_ids'].shape = ", orth['enc_input_ids'].shape)
labels = orth['enc_input_ids'][:,1:]
print("orth['enc_input_ids'][:,1:] = ", labels)
preds = torch.argmax(z['orth'], dim=1)
print("torch.argmax(z['orth'], dim=1) = ", preds)
accuracy = (preds == labels).sum() / len(labels)
print("accuracy = ", accuracy)

z['orth'].shape torch.Size([5, 49, 4])
z['orth'] =  tensor([[[ 7.3423e-02, -1.0104e+00, -3.1988e-01,  7.0081e-01],
         [ 4.1294e-01,  3.6833e-01, -6.0337e-01, -3.9756e-01],
         [ 3.6940e-01, -1.5503e-01, -2.0064e-01,  1.6927e-01],
         [-1.7370e-01,  7.4545e-01, -8.2421e-01,  8.4368e-01],
         [-3.6050e-01,  1.7056e-01,  1.8763e-02,  1.3118e-01],
         [ 5.2281e-01, -1.2056e-01, -3.8111e-01,  6.4269e-01],
         [-7.5891e-02, -6.5556e-01,  3.3835e-01,  2.7948e-01],
         [ 3.3343e-01,  6.4739e-01, -4.3987e-02,  8.8123e-01],
         [-1.2045e-01,  4.6238e-01, -2.0916e-01,  4.6143e-01],
         [-7.5457e-01, -8.2014e-01, -3.7641e-01, -2.2010e-01],
         [-8.2575e-01, -2.7183e-01, -1.2778e+00, -8.1094e-02],
         [-6.3467e-01, -6.0269e-01, -1.9329e-01, -6.3944e-02],
         [ 2.7073e-01,  1.1343e-01,  2.8926e-01,  3.7735e-01],
         [-5.2974e-01, -7.2577e-01,  5.2034e-01,  5.1274e-01],
         [ 9.5947e-01,  1.1378e+00, -3.5516e-01,  7.6983e-01],
   

In [26]:
preds

tensor([[16, 16, 43, 38],
        [16, 37, 43, 38],
        [16, 16, 43, 38],
        [38, 43, 43, 38],
        [38, 44, 42, 38]])

In [27]:
labels

tensor([[11, 29,  1,  4],
        [29, 18, 15,  1],
        [11, 24, 14,  1],
        [35, 25, 31,  1],
        [33, 11, 29,  1]])

In [25]:
preds == labels

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [35]:
print("z['phon'].shape", z['phon'].shape)
print("z['phon'] = ", z['phon'])
torch.argmax(z['phon'], dim=1)

z['phon'].shape torch.Size([5, 2, 4, 33])
z['phon'] =  tensor([[[[ 0.4780, -0.6079,  0.6687,  ...,  0.0773,  0.0718,  0.5552],
          [ 0.1672, -0.2810,  0.2328,  ...,  0.2251, -0.3893, -0.3242],
          [ 0.8086, -0.8917,  1.0724,  ...,  1.1364,  0.3756,  0.3942],
          [ 0.5570, -0.5401,  0.4696,  ...,  0.5681, -0.0911,  0.4643]],

         [[ 0.1455, -0.1109, -0.1953,  ..., -0.5642, -0.5088,  0.4320],
          [ 0.3923, -0.8616, -0.1826,  ..., -0.7779,  0.0059, -0.2665],
          [-0.5334,  0.0481, -0.3345,  ...,  0.1287,  0.4419,  0.0799],
          [ 0.5083, -0.3594, -0.0248,  ..., -0.7402, -0.2559,  0.1193]]],


        [[[ 0.4243, -0.5763,  0.9033,  ..., -0.2028,  0.4345,  0.5487],
          [ 0.1323,  0.0735,  0.5728,  ...,  0.6446,  0.1687, -0.4905],
          [ 0.7618, -1.3454,  0.8989,  ..., -0.0811,  0.4465,  0.3425],
          [ 0.4674, -0.7377,  0.5986,  ...,  0.3723,  0.3220,  0.4267]],

         [[ 0.0974, -0.1940, -0.4095,  ..., -0.2966, -0.7366,  0.4630],
 

tensor([[[0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
          0, 1, 0, 1, 1, 0, 0, 0, 0, 0],
         [1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
          0, 1, 1, 0, 0, 0, 0, 0, 1, 1],
         [0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
          0, 1, 1, 0, 0, 0, 0, 0, 1, 0],
         [0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
          0, 1, 1, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
          0, 1, 0, 1, 1, 0, 0, 0, 0, 0],
         [0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
          0, 1, 1, 0, 0, 0, 0, 0, 0, 1],
         [0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
          0, 1, 1, 0, 0, 0, 0, 1, 1, 0],
         [1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
          0, 1, 1, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 1, 0, 0, 1, 1, 1, 1, 0,

In [36]:
orth

{'enc_input_ids': tensor([[ 0, 11, 29,  1,  4],
         [ 0, 29, 18, 15,  1],
         [ 0, 11, 24, 14,  1],
         [ 0, 35, 25, 31,  1],
         [ 0, 33, 11, 29,  1]]),
 'dec_input_ids': tensor([[ 0, 11, 29,  4],
         [ 0, 29, 18, 15],
         [ 0, 11, 24, 14],
         [ 0, 35, 25, 31],
         [ 0, 33, 11, 29]]),
 'enc_pad_mask': tensor([[False, False, False, False,  True],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]]),
 'dec_pad_mask': tensor([[False, False, False,  True],
         [False, False, False, False],
         [False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]])}

In [43]:
logits = m(orth['enc_input_ids'], orth['enc_pad_mask'],
                orth['dec_input_ids'], orth['dec_pad_mask'],
                phon['enc_input_ids'], phon['enc_pad_mask'],
                phon['dec_input_ids'], phon['dec_pad_mask'])
        
orth_loss = torch.nn.CrossEntropyLoss(ignore_index=4)(logits['orth'], orth['enc_input_ids'][:,1:]) 
phon_loss = torch.nn.CrossEntropyLoss(ignore_index=2)(logits['phon'], phon['targets'])
loss = orth_loss + phon_loss

In [44]:
z_prime = m.generate(orth_enc_input=orth, 
                     orth_enc_pad_mask=torch.zeros_like(orth).bool(), 
                     phon_enc_input=phon, 
                     phon_enc_pad_mask=torch.zeros_like(phon).bool(), 
                     deterministic=True)['orth'][:, 1:]
z_prime


TypeError: zeros_like(): argument 'input' (position 1) must be Tensor, not dict

In [28]:

#assert z.item() == z_prime.item()

################# Check Phonology ########################
z = m(orth, 
      torch.zeros_like(orth).bool(), 
      orth, 
      torch.zeros_like(orth).bool(),
      [[phon][0]], 
      torch.zeros_like(phon).bool(), 
      [[phon][0]], 
      torch.zeros_like(phon).bool()
)['phon']; z


tensor([[[[ 0.6767, -0.1219, -0.5411,  0.1170, -0.3387, -0.1288, -0.5503,
            0.6902,  0.1972, -0.2650,  0.5467,  0.9316,  0.4024, -0.4422,
           -0.1477,  0.7241, -0.9001, -0.2532,  0.5851,  1.1965, -0.7901,
            0.2979, -0.0242,  0.4706,  0.8686,  0.1165,  0.4917,  0.5010,
           -0.1539, -0.0028,  0.1609, -0.2441,  0.3435]],

         [[ 0.5110,  0.4595, -0.6616,  0.0228, -0.6862,  0.1313,  0.8328,
            0.2021,  0.2570,  0.8814,  0.1321, -0.1988, -0.1504, -0.1617,
            0.7846, -0.2460,  0.9513, -0.4330, -0.6739,  0.0562,  0.5938,
            0.0119, -0.3092, -0.0674,  0.9380,  0.5049,  0.0826, -0.9075,
            0.3517,  0.6457,  0.2784, -0.3076,  0.8851]]]],
       grad_fn=<TransposeBackward0>)

In [39]:

z_prime = m.generate(orth, 
                     torch.zeros_like(orth).bool(), 
                     [[phon][0]], 
                     torch.zeros_like(phon).bool(), 
                     deterministic=True)['phon']
z_prime

#assert (torch.where(z[0].argmax(dim=0) == 1)[1] == z_prime[0][1]).all()
print(len(z_prime[0]))

20


In [42]:
B,C,E = 2,3,4
a = torch.rand((B,C,E))

In [44]:
print(a.shape)
print(a.transpose(1,2).shape)

torch.Size([2, 3, 4])
torch.Size([2, 4, 3])


In [62]:
p=torch.rand((1,2,33)); p

tensor([[[0.4301, 0.9611, 0.7723, 0.9204, 0.1864, 0.3543, 0.0298, 0.9956,
          0.0215, 0.8572, 0.2218, 0.4789, 0.0823, 0.7532, 0.1532, 0.0425,
          0.4336, 0.8475, 0.8205, 0.8800, 0.2938, 0.7716, 0.4422, 0.3135,
          0.1729, 0.0260, 0.9826, 0.9753, 0.2033, 0.6105, 0.4312, 0.0927,
          0.9542],
         [0.7559, 0.8657, 0.4542, 0.3938, 0.1533, 0.3608, 0.4802, 0.3396,
          0.7139, 0.2800, 0.1930, 0.4848, 0.7758, 0.4037, 0.2637, 0.3022,
          0.6368, 0.4707, 0.4163, 0.9229, 0.5459, 0.4463, 0.9723, 0.4306,
          0.7044, 0.4951, 0.3131, 0.5019, 0.4948, 0.4797, 0.4198, 0.3487,
          0.9346]]])

In [78]:
torch.bernoulli(p[:,1,:])

tensor([[1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1.,
         1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1.]])

In [70]:
torch.bernoulli(p)[0]

tensor([[1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
         1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1.],
        [1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1.,
         0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1.]])

In [80]:
p[:,1]

tensor([[0.7559, 0.8657, 0.4542, 0.3938, 0.1533, 0.3608, 0.4802, 0.3396, 0.7139,
         0.2800, 0.1930, 0.4848, 0.7758, 0.4037, 0.2637, 0.3022, 0.6368, 0.4707,
         0.4163, 0.9229, 0.5459, 0.4463, 0.9723, 0.4306, 0.7044, 0.4951, 0.3131,
         0.5019, 0.4948, 0.4797, 0.4198, 0.3487, 0.9346]])

In [84]:
torch.where(p[:,1] > 0.5)[1]

tensor([ 0,  1,  8, 12, 16, 19, 20, 22, 24, 27, 32])

In [173]:
chkpt = torch.load('models/model0_checkpoint99.pth', map_location=torch.device('cpu'))
m = Model(len(ds.character_tokenizer), len(ds.phonology_tokenizer), d_model=chkpt['d_model'], nhead=chkpt['nhead'])
m.load_state_dict(chkpt['model'])
m.eval();

In [178]:
idx = 10040
word = ds.words[idx:idx+1]
print("word = ", word)
batch = ds[idx:idx+1]
#print("batch = ", batch)
orth, phon = batch['orthography'].to('cpu'), batch['phonology'].to('cpu')
orthography = orth['enc_input_ids']
orthography_mask = orth['enc_pad_mask']
phonology = phon['enc_input_ids']
phonology_mask = phon['enc_pad_mask']

word =  ['sam']


In [179]:
generation = m.generate(orthography, orthography_mask, phonology, phonology_mask, deterministic=False)

In [180]:
ds.character_tokenizer.decode(generation['orth'][:,:].tolist())

['[BOS]ci”γ[EOS][EOS][EOS][EOS][EOS][EOS][EOS][EOS][EOS][EOS][EOS][EOS]γ[EOS]γ']

In [181]:
generation['phon'][0]

[tensor([31]),
 tensor([ 9, 14]),
 tensor([14, 15, 17, 26, 28, 29]),
 tensor([32]),
 tensor([32]),
 tensor([32]),
 tensor([32]),
 tensor([32]),
 tensor([32]),
 tensor([32]),
 tensor([32]),
 tensor([32]),
 tensor([32]),
 tensor([32]),
 tensor([32]),
 tensor([32]),
 tensor([32]),
 tensor([14, 18]),
 tensor([32]),
 tensor([32])]

In [ ]:
ds.phonology_tokenizer.decode(generation['phon'][0])

In [148]:
print(ds.character_tokenizer.vocab)

['[BOS]', '[EOS]', '[CLS]', '[UNK]', '[PAD]', 'i', '’', '\x80', 'o', 'f', 'โ', 'v', '“', '.', ',', 'r', "'", '\x9d', '\x9c', 'g', 'k', 'c', 'n', 'm', 'z', '-', 'y', 'e', 'h', 'j', 'p', 'x', 's', '"', 'q', '\x94', 'ç', '¥', 'w', '”', 'l', 'a', '!', 'u', 'b', 'd', 't', '—', 'γ']


In [158]:
ds

['__add__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__orig_bases__',
 '__parameters__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_is_protocol',
 'character_tokenizer',
 'dataset',
 'phonology_tokenizer',
 'words']